# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: build image
        run: docker build -t tekoe1985/my-portfolio .
      # Configure AWS credentials from GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # Change to your AWS region
      # Login to Amazon ECR  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

       # Build, Tag, and Push the image to ECR
      - name: Build, Tag, and Push image
        run: |
          IMAGE_REPO_NAME=github-action        # Change to your repo name
          IMAGE_TAG=latest                # Or use ${{ github.sha }} for unique tags
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}

          # Build Docker image
           docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

          # Tag image with full ECR path
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG

          # Push image to ECR
          docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG

      
      # Runs a set of commands using the runners shell
      #- name: Push image
       # run: |
        #     docker login -u tekoe1985  ${{secrets.REGISTRY_PASS}}
         #    docker push tekoe1985/my-portfolio
      
